[project]
name = "comlink_ipc"
version = "0.4.0"
description = "Simple IPC inspired by comlink.js"
authors = [{ name = "lirrensi", email = "you@example.com" }]
license = {text = "MIT"}
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
